### ISSUE TITLE
persist experiments

### ISSUE THREAD

**Issue by durandom** [AICoE/experiment-tracking#6]
https://paas.upshift.redhat.com/console/project/aiops-kubeflow/browse/pods/mlflow-server-d4bb7f599-tq64g?tab=details

It seems we loose the experiment db if the container restarts. Can we make that persistent?

**Comment by zmhassan** [comment]
We can make it persistent with a persistent volume.

**Comment by zmhassan** [comment]
mount the following folder: `/opt/app-root/src/mlruns`. They have already merged the ceph storage patch so we may switch to using MLFlow_S3_endpoint env vars later. But temporarily this is the move.

**Comment by durandom** [comment]
can you add the PVC and mount to the deployment config and re-deploy on upshift?

**Comment by zmhassan** [comment]
Yes this is doable.

**Comment by goern** [comment]
can we push this to backlog, turn this into a trello card, and close this issue?
